// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPkbCORsjCQb-JyiARufTMEHFwsbuCHk',
    appId: '1:696937115487:web:5e000ff541b51ada8a10ea',
    messagingSenderId: '696937115487',
    projectId: 'meroquiz-55601',
    authDomain: 'meroquiz-55601.firebaseapp.com',
    storageBucket: 'meroquiz-55601.appspot.com',
    measurementId: 'G-RVTGD7DKGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiw6QDR8OLCO5BOO74Xqrilqu5Tww200',
    appId: '1:696937115487:android:eb3cbdb8d4938be78a10ea',
    messagingSenderId: '696937115487',
    projectId: 'meroquiz-55601',
    storageBucket: 'meroquiz-55601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJx7t0ameTlWAhFmQM0bIiLv9JljIJuM',
    appId: '1:696937115487:ios:44e79e401ed9398b8a10ea',
    messagingSenderId: '696937115487',
    projectId: 'meroquiz-55601',
    storageBucket: 'meroquiz-55601.appspot.com',
    iosClientId: '696937115487-32atnadfrec11t6006njsfstg14u2hhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.meroquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJx7t0ameTlWAhFmQM0bIiLv9JljIJuM',
    appId: '1:696937115487:ios:44e79e401ed9398b8a10ea',
    messagingSenderId: '696937115487',
    projectId: 'meroquiz-55601',
    storageBucket: 'meroquiz-55601.appspot.com',
    iosClientId: '696937115487-32atnadfrec11t6006njsfstg14u2hhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.meroquiz',
  );
}
